### ISSUE TITLE
Crash when completion

### ISSUE THREAD

**Issue by SilverRainZ** [SrainApp/srain#323]
```
0x000055555558a678 in sui_user_get_nickname ()
#0  0x000055555558a678 in sui_user_get_nickname ()
#1  0x000055555558af31 in sui_user_list_get_users_by_prefix ()
#2  0x000055555557e453 in sui_chat_buffer_completion_func ()
#3  0x000055555557bd2a in sui_buffer_completion_func ()
#4  0x000055555557f361 in reset_state ()
#5  0x000055555557f756 in sui_completion_complete ()
#6  0x000055555558c520 in input_text_view_on_key_press ()
#7  0x00007ffff7876f0b in  () at /usr/lib/libgtk-3.so.0
#8  0x00007ffff737cd8f in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#9  0x00007ffff7398588 in  () at /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff739927b in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff739a1a0 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#12 0x00007ffff7b326f5 in  () at /usr/lib/libgtk-3.so.0
#13 0x00007ffff7b4189c in gtk_window_propagate_key_event () at /usr/lib/libgtk-3.so.0
#14 0x00007ffff7b43efc in  () at /usr/lib/libgtk-3.so.0
#15 0x00007ffff78771e5 in  () at /usr/lib/libgtk-3.so.0
#16 0x00007ffff739a030 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#17 0x00007ffff739a1a0 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#18 0x00007ffff7b326f5 in  () at /usr/lib/libgtk-3.so.0
#19 0x00007ffff79d0482 in  () at /usr/lib/libgtk-3.so.0
#20 0x00007ffff79d12d3 in gtk_main_do_event () at /usr/lib/libgtk-3.so.0
#21 0x00007ffff77317f3 in  () at /usr/lib/libgdk-3.so.0
#22 0x00007ffff7764ce4 in  () at /usr/lib/libgdk-3.so.0
--Type <RET> for more, q to quit, c to continue without paging--sg
#23 0x00007ffff728910c in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#24 0x00007ffff72dcb99 in  () at /usr/lib/libglib-2.0.so.0
#25 0x00007ffff7286871 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#26 0x00007ffff74928b6 in g_application_run () at /usr/lib/libgio-2.0.so.0
#27 0x0000555555560131 in main ()
A debugging session is active.
```

**Comment by SilverRainZ** [comment]
Should be fixed by #320
