### ISSUE TITLE
Crash when rendering channel topic

### ISSUE THREAD

**Issue by SilverRainZ** [SrainApp/srain#355]
The reason may be:`srn_message_new` is also used to render  channel topic to cairo markup, but #345 had not consider this.

```
** (srain:147627): WARNING **: 22:15:56.217: (../src/core/message.c:82):srn_message_new: code should not be reached
**
GLib:ERROR:../glib/glib/gdatetime.c:2207:g_date_time_get_ymd: assertion failed: (0 <= remaining_days)
Bail out! GLib:ERROR:../glib/glib/gdatetime.c:2207:g_date_time_get_ymd: assertion failed: (0 <= remaining_days)

Thread 1 "srain" received signal SIGABRT, Aborted.
0x00007ffff6c7bd22 in raise () from /usr/lib/libc.so.6
#0  0x00007ffff6c7bd22 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff6c65862 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff723f094 in  () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff729d0c1 in g_assertion_message_expr () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff725c8dc in g_date_time_get_ymd () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff725d15c in g_date_time_get_year () at /usr/lib/libglib-2.0.so.0
#6  0x00007ffff725e1d3 in g_date_time_get_day_of_month () at /usr/lib/libglib-2.0.so.0
#7  0x00007ffff725f301 in  () at /usr/lib/libglib-2.0.so.0
#8  0x00007ffff725fbae in g_date_time_format () at /usr/lib/libglib-2.0.so.0
#9  0x000055555557e262 in filter (msg=0x5555567a9890) at ../src/filter/log_filter.c:56
#10 0x000055555557e219 in srn_filter_message (msg=0x5555567a9890, flags=7) at ../src/filter/filter.c:75
#11 0x0000555555576ff3 in srn_chat_add_misc_message_with_user
    (self=0x5555558f8c70, user=0x5555558b8b60, content=0x5555566e90c0 "频道的主题是：\n\tWelcome to #srain!  Use disscussion https://git.io/JOf96 if no one response | We are moving towards GTK4   | Version: 1.3.1 | Home: https://srain.im | Documentation: https://doc"..., context=0x5555558b8d00) at ../src/core/chat.c:351
#12 0x00005555555770fa in srn_chat_add_misc_message_with_user_fmt
    (self=0x5555558f8c70, user=0x5555558b8b60, context=0x5555558b8d00, fmt=0x7ffff7fc60bb "频道的主题是：\n\t%1$s") at ../src/core/chat.c:370
#13 0x00005555555733fd in irc_event_numeric
--Type <RET> for more, q to quit, c to continue without paging--
    (sirc=0x555555e58f10, event=332, origin=0x55555586c450 "strontium.libera.chat", params=0x5555558b8d60, count=3, context=0x5555558b8d00) at ../src/core/app_irc_event.c:1604
#14 0x000055555558933d in _sirc_event_hdr (sirc=0x555555e58f10, imsg=0x5555558b8d20, context=0x5555558b8d00) at ../src/sirc/sirc_event_hdr.c:108
#15 0x0000555555588f4b in sirc_event_hdr (sirc=0x555555e58f10, imsg=0x5555558b8d20) at ../src/sirc/sirc_event_hdr.c:61
#16 0x0000555555586e21 in on_recv_ready (obj=0x7fffe800c690, res=0x5555566d66e0, user_data=0x555555e58f10) at ../src/sirc/sirc.c:242
#17 0x00007ffff742c760 in  () at /usr/lib/libgio-2.0.so.0
#18 0x00007ffff745ed34 in  () at /usr/lib/libgio-2.0.so.0
#19 0x00007ffff745ed6d in  () at /usr/lib/libgio-2.0.so.0
#20 0x00007ffff7276fd3 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#21 0x00007ffff72cd049 in  () at /usr/lib/libglib-2.0.so.0
#22 0x00007ffff7274545 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#23 0x00007ffff74966ee in g_application_run () at /usr/lib/libgio-2.0.so.0
#24 0x000055555558c2a9 in sui_application_run (self=0x555555638140, argc=1, argv=0x7fffffffe368) at ../src/sui/sui_app.c:297
#25 0x000055555558f24b in sui_run_application (app=0x555555638140, argc=1, argv=0x7fffffffe368) at ../src/sui/sui.c:65
#26 0x000055555556d0dd in srn_application_run (app=0x555555602f40, argc=1, argv=0x7fffffffe368) at ../src/core/app.c:122
#27 0x000055555557db3f in main (argc=1, argv=0x7fffffffe368) at ../src/core/srain.c:56
```

**Comment by progval** [comment]
Oops, I messed up the refcount. Sent a fix in GH-356
